## Tables {#sec-tables}
 
```{r} 
#| label: 'set-rda-dir-tbls'
#| echo: false 
#| warning: false 
#| eval: true 
#| include: false
library(flextable)
rda_dir <- 'C:/Users/Megumi.Oshima/Documents/workflow_workthrough/rda_files'
``` 

```{r} 
#| label: 'tbl-bnc-setup'
#| echo: false 
#| warning: false 
#| eval: true 
#| include: false
# if the bnc table rda exists:
if (file.exists(file.path(rda_dir, 'bnc_table.rda'))){

  # load rda
  load(file.path(rda_dir, 'bnc_table.rda'))

  # save rda with plot-specific name
  bnc_table_rda <- rda

  # remove generic rda object
  rm(rda)

  # save table, caption as separate objects; set eval to TRUE
  bnc_table <- bnc_table_rda$table
  bnc_cap <- bnc_table_rda$cap
  eval_bnc <- TRUE

# if the bnc table rda does not exist, don't evaluate the next chunk
} else {eval_bnc <- FALSE}
``` 

::: {.landscape}

```{r} 
#| label: 'tbl-bnc'
#| echo: false 
#| warning: false 
#| eval: !expr eval_bnc 
#| tbl-cap: !expr if(eval_bnc) bnc_cap 
#| include: !expr eval_bnc
bnc_table |>
                flextable::fit_to_width(max_width = 8)
``` 

:::

{{< pagebreak >}}
```{r} 
#| label: 'tbl-indices-setup'
#| echo: false 
#| warning: false 
#| eval: true 
#| include: false
# if the indices table rda exists:
if (file.exists(file.path(rda_dir, 'indices.abundance_table.rda'))){

  # load rda
  load(file.path(rda_dir, 'indices.abundance_table.rda'))

  # save rda with plot-specific name
  indices_table_rda <- rda

  # remove generic rda object
  rm(rda)

  # save table, caption as separate objects; set eval to TRUE
  indices_table <- indices_table_rda$table
  indices_cap <- indices_table_rda$cap
  eval_indices <- TRUE

# if the indices table rda does not exist, don't evaluate the next chunk
} else {eval_indices <- FALSE}
``` 

::: {.landscape}

```{r} 
#| label: 'tbl-indices'
#| echo: false 
#| warning: false 
#| eval: !expr eval_indices 
#| tbl-cap: !expr if(eval_indices) indices_cap 
#| include: !expr eval_indices
indices_table |>
                flextable::fit_to_width(max_width = 8)
``` 

:::

{{< pagebreak >}}
```{r} 
#| label: 'tbl-landings-setup'
#| echo: false 
#| warning: false 
#| eval: true 
#| include: false
# if the landings table rda exists:
if (file.exists(file.path(rda_dir, 'landings_table.rda'))){

  # load rda
  load(file.path(rda_dir, 'landings_table.rda'))

  # save rda with plot-specific name
  landings_table_rda <- rda

  # remove generic rda object
  rm(rda)

  # save table, caption as separate objects; set eval to TRUE
  landings_table <- landings_table_rda$table
  landings_cap <- landings_table_rda$cap
  eval_landings <- TRUE

# if the landings table rda does not exist, don't evaluate the next chunk
} else {eval_landings <- FALSE}
``` 

```{r} 
#| label: 'tbl-landings'
#| echo: false 
#| warning: false 
#| eval: !expr eval_landings 
#| tbl-cap: !expr if(eval_landings) landings_cap 
#| include: !expr eval_landings
landings_table
``` 


{{< pagebreak >}}
